steps:
  - id: 'List repository folder'
    name: golang
    args: ['ls', '-lah']
    env: ['GOPATH=/workspace']
  - id: 'Running Unit Tests'
    name: golang
    args: ['go', 'test', './...']
    env: ['GOPATH=/workspace']
    # - id: 'Running docker compose'
    #   name: 'docker/compose'
    #   args: ['-f', 'docker-compose-ci.yml', 'up', '-d']
    #   env: ['GOPATH=/go']
    # - id: 'Running Unit Tests'
    #   name: docker
    #   args: ['exec', '-t', 'golang_desafio_ci', 'go', 'test', 'tests/arithmetics_test.go']
    #   env: ['GOPATH=/go']
    # - id: 'List workspace dir'
    #   name: golang
    #   args: ['ls', '-lah', '/workspace']
    #   env: ['GOPATH=/go']
    # - id: 'Move Files to src'
    #   name: golang
    #   args: ['mv', '/go/*', '/workspace/src/golang-fullcycle-desafio-ci']
    #   env: ['GOPATH=/go']
    # - id: 'List files'
    #   name: golang
    #   args: ['ls', '-lah']
    #   env: ['GOPATH=/go']
    # - id: 'Running Unit Tests'
    #   name: golang
    #   args: ['go', 'test', 'tests/arithmetics_test.go']
    #   env: ['GOPATH=/go']
