steps:
    - id: 'Move Files to src'
      name: golang
      args: ['mv', '/workspace/*', '/workspace/src/golang-fullcycle-desafio-ci']
      env: ['GOPATH=/workspace']
    - id: 'List files'
      name: golang
      args: ['ls', '-lah']
      env: ['GOPATH=/workspace']
    - id: 'Running Unit Tests'
      name: golang
      args: ['go', 'test', 'tests/arithmetics_test.go']
      env: ['GOPATH=/workspace']
