steps:
    - id: 'PWD'
      name: golang
      args: ['pwd']
    - id: 'List'
      name: golang
      args: ['ls', '-lah']
    - id: 'Running Unit Tests'
      name: golang
      args: ['go', 'test', 'tests/arithmetics_test.go']
