steps:
  - id: 'List workspace files'
    name: golang
    args: ['ls', '-lah']
  - id: 'pwd workspace files'
    name: golang
    args: ['ls', '-lah']
  - id: 'Create project folder into go workspace'
    name: golang
    args: ['mkdir', '-p', '/go/src/golang-fullcycle-desafio-ci']
    env: ['GOPATH=/go']
  - id: 'Move project code to go workspace'
    name: golang
    args: ['mv', '/workspace/*', '/go/src/golang-fullcycle-desafio-ci']
    env: ['GOPATH=/go']
  - id: 'List golang-fullcycle-desafio-ci dir'
    name: golang
    args: ['ls', '-lah', '/go/src/golang-fullcycle-desafio-ci']
    env: ['GOPATH=/go']
  - id: 'Running Unit Tests'
    name: golang
    args: ['go', 'test', './...']
    env: ['GOPATH=/go']
    # - id: 'Running docker compose'
    #   name: 'docker/compose'
    #   args: ['-f', 'docker-compose-ci.yml', 'up', '-d']
    #   env: ['GOPATH=/go']
    # - id: 'Running Unit Tests'
    #   name: docker
    #   args: ['exec', '-t', 'golang_desafio_ci', 'go', 'test', 'tests/arithmetics_test.go']
    #   env: ['GOPATH=/go']
    # - id: 'List workspace dir'
    #   name: golang
    #   args: ['ls', '-lah', '/workspace']
    #   env: ['GOPATH=/go']
    # - id: 'Move Files to src'
    #   name: golang
    #   args: ['mv', '/go/*', '/workspace/src/golang-fullcycle-desafio-ci']
    #   env: ['GOPATH=/go']
    # - id: 'List files'
    #   name: golang
    #   args: ['ls', '-lah']
    #   env: ['GOPATH=/go']
    # - id: 'Running Unit Tests'
    #   name: golang
    #   args: ['go', 'test', 'tests/arithmetics_test.go']
    #   env: ['GOPATH=/go']
