steps:
  - id: "Running docker compose"
    name: "docker/compose"
    args: ['-f', 'docker-compose-ci.yml', 'up', '-d']
  - id: 'Running Unit Tests'
    name: golang
    args: ['go', 'test', './...']
    env: ['GOPATH=/go']
  # - id: 'Create Go Workspace Source'
  #   name: 'docker'
  #   args: ['exec', '-t', 'golang_desafio_ci', 'mkdir', '-p', '/go/src/golang-fullcycle-desafio-ci']
  # - id: 'List Go Workspace Files'
  #   name: 'docker'
  #   args: ['exec', '-t', 'golang_desafio_ci', 'ls', '-lah', '/go/src/golang-fullcycle-desafio-ci']
  # - id: 'Build app'
  #   name: golang
  #   args: ['go', 'build', 'cmd/.']
  # - id: 'Running Unit Tests'
  #   name: golang
  #   args: ['go', 'test', './...']
  #   env: ['GOPATH=/workspace']