steps:
  # - id: 'Init'
  #   name: golang
  #   args: ['go', 'mod', 'init', 'golang-fullcycle-desafio-ci']
  - id: 'Build app'
    name: golang
    args: ['go', 'build', 'cmd/.']
  - id: 'Pwd app dir'
    name: golang
    args: ['pwd']
  - id: 'List workspace files'
    name: golang
    args: ['ls', '-lah']
  - id: 'Running Unit Tests'
    name: golang
    args: ['go', 'test', './...']